name: The Tiny Island Emporium
favicon: null
layout_spectrum: 0.5341734304092824
typography_spectrum: 0.9444104032590985
title: The Tiny Island Emporium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2521'
    - '#edc59b'
    - '#2ea4ee'
    - '#bc4b05'
  brandStrength: 0.1148071673233062
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
